version: '3.1'
name: qa_app
services:
  qa_backend:
    image: qa_app-backend:v0.01
    container_name: qa-app-backend
    build: ../backend/.
    restart: always
    ports:
      - "3000:3000"
    environment:
      SERVICE_PORT: 3000
      USE_HTTPS: false
      DB_HOST: "qa_database"
      DB_PORT: 27017
      DB_USER: "custom_user"
      DB_PASS: "custom_user_pass"
      DB_NAME: "qa_app"
    depends_on:
      - qa_database
    #     condition: service_healthy
  qa_database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "qa_app"
      CUSTOM_USERNAME: "custom_user"
      CUSTOM_USERPASS: "custom_user_pass"
    volumes:
      - ./db_init/db_init.js:/docker-entrypoint-initdb.d/db_init.js:ro
